//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TablePerson", Namespace="http://schemas.datacontract.org/2004/07/Command")]
    [System.SerializableAttribute()]
    public partial class TablePerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_cardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_card {
            get {
                return this.Id_cardField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_cardField, value) != true)) {
                    this.Id_cardField = value;
                    this.RaisePropertyChanged("Id_card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICommands")]
    public interface ICommands {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/SendRequest", ReplyAction="http://tempuri.org/ICommands/SendRequestResponse")]
        Client.ServiceReference1.SendRequestResponse SendRequest(Client.ServiceReference1.SendRequestRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/SendRequest", ReplyAction="http://tempuri.org/ICommands/SendRequestResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.SendRequestResponse> SendRequestAsync(Client.ServiceReference1.SendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/SetTablePerson", ReplyAction="http://tempuri.org/ICommands/SetTablePersonResponse")]
        void SetTablePerson(Client.ServiceReference1.TablePerson t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/SetTablePerson", ReplyAction="http://tempuri.org/ICommands/SetTablePersonResponse")]
        System.Threading.Tasks.Task SetTablePersonAsync(Client.ServiceReference1.TablePerson t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/GetTablePerson", ReplyAction="http://tempuri.org/ICommands/GetTablePersonResponse")]
        Client.ServiceReference1.TablePerson GetTablePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommands/GetTablePerson", ReplyAction="http://tempuri.org/ICommands/GetTablePersonResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.TablePerson> GetTablePersonAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string queryString;
        
        public SendRequestRequest() {
        }
        
        public SendRequestRequest(string queryString) {
            this.queryString = queryString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SendRequestResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public SendRequestResponse() {
        }
        
        public SendRequestResponse(System.Data.DataTable SendRequestResult, string message) {
            this.SendRequestResult = SendRequestResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandsChannel : Client.ServiceReference1.ICommands, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandsClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ICommands>, Client.ServiceReference1.ICommands {
        
        public CommandsClient() {
        }
        
        public CommandsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.SendRequestResponse Client.ServiceReference1.ICommands.SendRequest(Client.ServiceReference1.SendRequestRequest request) {
            return base.Channel.SendRequest(request);
        }
        
        public System.Data.DataTable SendRequest(string queryString, out string message) {
            Client.ServiceReference1.SendRequestRequest inValue = new Client.ServiceReference1.SendRequestRequest();
            inValue.queryString = queryString;
            Client.ServiceReference1.SendRequestResponse retVal = ((Client.ServiceReference1.ICommands)(this)).SendRequest(inValue);
            message = retVal.message;
            return retVal.SendRequestResult;
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.SendRequestResponse> SendRequestAsync(Client.ServiceReference1.SendRequestRequest request) {
            return base.Channel.SendRequestAsync(request);
        }
        
        public void SetTablePerson(Client.ServiceReference1.TablePerson t) {
            base.Channel.SetTablePerson(t);
        }
        
        public System.Threading.Tasks.Task SetTablePersonAsync(Client.ServiceReference1.TablePerson t) {
            return base.Channel.SetTablePersonAsync(t);
        }
        
        public Client.ServiceReference1.TablePerson GetTablePerson(int id) {
            return base.Channel.GetTablePerson(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.TablePerson> GetTablePersonAsync(int id) {
            return base.Channel.GetTablePersonAsync(id);
        }
    }
}
